# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: Learn / AWS
nav:
- Home: index.md
- Overview: overview.md
- 'AWS Account':  'account/account.md'
- 'AWS Login':  'login/login.md'
- 'AWS Command Line: CLI':  'cli/cli.md'
- 'Users and Roles':
  - 'Overview': 'users/overview.md'
  - 'IAM': 'users/iam/iam.md'
- 'Storage':
  - 'Overview': 'storage/overview.md'
  - 'S3': 'storage/s3/s3.md'
- 'Content Delivery Network':
  - 'Overview': 'cdn/overview.md'
  - 'CloudFront': 'cdn/cloudfront/cloudfront.md'
  - 'CloudFront + S3 Static Website':  'cdn/cloudfront/public-s3-bucket.md'
  - 'CloudFront + Lambda Function':  'cdn/cloudfront/private-auth-lambda.md'
- 'Virtual Machine':
  - 'Overview': 'vm/overview.md'
  - 'EC2': 'vm/ec2/ec2.md'
- 'Troubleshooting': 'troubleshooting/troubleshooting.md'
- 'Resources': resources.md
# ------- configuration properties ---------------
copyright:  Copyright Open Water Foundation
# Use extra CSS to customize styles, based on theme
extra_css:
  - 'css/extra-material-theme.css'
# ------------------------------------------------
# Google Analytics
# - see:  https://squidfunk.github.io/mkdocs-material/getting-started/#google-analytics
google_analytics:
 - 'UA-135465513-1'
 - auto
# Don't indicate the repo because Edit will be shown on every page (don't want that in deployed mode)
# - Also see edit_uri if repo_url is specified
#repo_url:  https://github.com/OpenWaterFoundation/owf-learn-mkdocs
site_description:  Open Water Foundation Learn AWS
site_author:  Open Water Foundation
# Use Material theme
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme:
 name: material
 favicon:  'images/OWF-Logo-Favicon-32x32.png'
